name: Maven CI
run-name: ${{ github.actor }} Maven CI

on:
  push:
    branches:
      - main
      - master

jobs:

  ##########################################
  #       BUILD & PACKAGING & TEST
  ##########################################
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: .

    steps:

    # Récupération du contenu du répertoire dans l'image 'ubuntu'
    - uses: actions/checkout@v2

    # Set up du jdk
    - name: Set up JDK 21
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: '21'
        cache: 'maven'
  
     # Compilation & packaging
    - name: Compilation & Packaging
      run: mvn -DskipTests=true clean package

    # Test
    - name: Test
      run: mvn test
     
    # Stockage de l'archive sur le depôt Github
    - name: Upload build artifacts
      uses: actions/upload-artifact@v4
      with:        
        name: itsf.war
        path: target/itsf.war


  ##########################################
  #         PUSH ON DOCKER HUB
  ##########################################
  push:
    runs-on: ubuntu-latest
    needs: build
    defaults:
      run:
        working-directory: .

    steps:
    # Récupération du contenu du répertoire dans l'image 'ubuntu'
    - uses: actions/checkout@v2

    # Récupération du répertoire 'target' et de sont contenu (archive 'itsf.war')
    - uses: actions/download-artifact@v4
      with:        
        name: itsf.war
        path: target/itsf.war

    # List le répertoire '/home/runner/work/junit/junit'
    - name: List file
      run: pwd && ls -l

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v2

    - name: Set up Docker Buidlx
      uses: docker/setup-buildx-action@v3

    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.GITHUBUSERNAME }}
        password: ${{ secrets.GITHUBTOKEN }}
      
    - name: Build and push
      uses: docker/build-push-action@v5
      with:
        context: .
        file: ./Dockerfile
        push: true
        tags: gizaoui/itsf:1.0.0
